package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Fase generated by hbm2java
 */
public class Fase implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idFase;
    private String descripcion;
    private Set<Recorrido> recorridos = new HashSet<Recorrido>(0);
    private Set<ProgramaFase> programaFases = new HashSet<ProgramaFase>(0);
    private Set<FaseGrupo> faseGrupos = new HashSet<FaseGrupo>(0);

    public Fase() {
    }

    public Fase(String descripcion, Set<Recorrido> recorridos, Set<ProgramaFase> programaFases, Set<FaseGrupo> faseGrupos) {
        this.descripcion = descripcion;
        this.recorridos = recorridos;
        this.programaFases = programaFases;
        this.faseGrupos = faseGrupos;
    }

    public Integer getIdFase() {
        return this.idFase;
    }

    public void setIdFase(Integer idFase) {
        this.idFase = idFase;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<Recorrido> getRecorridos() {
        return this.recorridos;
    }

    public void setRecorridos(Set<Recorrido> recorridos) {
        this.recorridos = recorridos;
    }

    public Set<ProgramaFase> getProgramaFases() {
        return this.programaFases;
    }

    public void setProgramaFases(Set<ProgramaFase> programaFases) {
        this.programaFases = programaFases;
    }

    public Set<FaseGrupo> getFaseGrupos() {
        return this.faseGrupos;
    }

    public void setFaseGrupos(Set<FaseGrupo> faseGrupos) {
        this.faseGrupos = faseGrupos;
    }

}
