package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo implements java.io.Serializable, Comparable<Grupo> {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idGrupo;
    private String descripcion;
    private Set<Recorrido> recorridos = new HashSet<Recorrido>(0);
    private Set<FaseGrupo> faseGrupos = new HashSet<FaseGrupo>(0);

    public Grupo() {
    }

    public Grupo(String descripcion, Set<Recorrido> recorridos, Set<FaseGrupo> faseGrupos) {
        this.descripcion = descripcion;
        this.recorridos = recorridos;
        this.faseGrupos = faseGrupos;
    }

    public Integer getIdGrupo() {
        return this.idGrupo;
    }

    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<Recorrido> getRecorridos() {
        return this.recorridos;
    }

    public void setRecorridos(Set<Recorrido> recorridos) {
        this.recorridos = recorridos;
    }

    public Set<FaseGrupo> getFaseGrupos() {
        return this.faseGrupos;
    }

    public void setFaseGrupos(Set<FaseGrupo> faseGrupos) {
        this.faseGrupos = faseGrupos;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Grupo [idGrupo=" + idGrupo + ", descripcion=" + descripcion + "]";
    }

    @Override
    public int compareTo(Grupo o) {
        final int MENOR = -1;
        final int MAYOR = 1;
        final int IGUAL = 0;
        int esteId = new Integer(this.getIdGrupo());
        int otroId = new Integer(o.getIdGrupo());
        if (this == o) {
            return IGUAL;
        }
        if (esteId < otroId) {
            return MENOR;
        }
        if (esteId > otroId) {
            return MAYOR;
        }
        return IGUAL;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((idGrupo == null) ? 0 : idGrupo.hashCode());
        return result;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Grupo other = (Grupo) obj;
        if (idGrupo == null) {
            if (other.idGrupo != null)
                return false;
        } else if (!idGrupo.equals(other.idGrupo))
            return false;
        return true;
    }



}
