package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Motivo generated by hbm2java
 */
public class Motivo implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idMotivo;
    private String descripcion;
    private Set<Recorrido> recorridos = new HashSet<Recorrido>(0);

    public Motivo() {
    }

    public Motivo(String descripcion, Set<Recorrido> recorridos) {
        this.descripcion = descripcion;
        this.recorridos = recorridos;
    }

    public Integer getIdMotivo() {
        return this.idMotivo;
    }

    public void setIdMotivo(Integer idMotivo) {
        this.idMotivo = idMotivo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<Recorrido> getRecorridos() {
        return this.recorridos;
    }

    public void setRecorridos(Set<Recorrido> recorridos) {
        this.recorridos = recorridos;
    }

    @Override
    public String toString() {
        return "Motivo [idMotivo=" + idMotivo + ", descripcion=" + descripcion + "]";
    }

}
