package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idPersona;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private String activo;
    private Set<Recorrido> recorridos = new HashSet<Recorrido>(0);
    private Set<RolPersona> rolPersonas = new HashSet<RolPersona>(0);

    public Persona() {
    }

    public Persona(String nombre, String apellido1, String apellido2, String activo, Set<Recorrido> recorridos, Set<RolPersona> rolPersonas) {
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.activo = activo;
        this.recorridos = recorridos;
        this.rolPersonas = rolPersonas;
    }

    public Integer getIdPersona() {
        return this.idPersona;
    }

    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido1() {
        return this.apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return this.apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getActivo() {
        return this.activo;
    }

    public void setActivo(String activo) {
        this.activo = activo;
    }

    public Set<Recorrido> getRecorridos() {
        return this.recorridos;
    }

    public void setRecorridos(Set<Recorrido> recorridos) {
        this.recorridos = recorridos;
    }

    public Set<RolPersona> getRolPersonas() {
        return this.rolPersonas;
    }

    public void setRolPersonas(Set<RolPersona> rolPersonas) {
        this.rolPersonas = rolPersonas;
    }

}
