package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

/**
 * ProgramaFase generated by hbm2java
 */
public class ProgramaFase implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idProgramaFase;
    private Fase fase;
    private Programa programa;

    public ProgramaFase() {
    }

    public ProgramaFase(Fase fase, Programa programa) {
        this.fase = fase;
        this.programa = programa;
    }

    public Integer getIdProgramaFase() {
        return this.idProgramaFase;
    }

    public void setIdProgramaFase(Integer idProgramaFase) {
        this.idProgramaFase = idProgramaFase;
    }

    public Fase getFase() {
        return this.fase;
    }

    public void setFase(Fase fase) {
        this.fase = fase;
    }

    public Programa getPrograma() {
        return this.programa;
    }

    public void setPrograma(Programa programa) {
        this.programa = programa;
    }

}
