package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Recorrido generated by hbm2java
 */
public class Recorrido implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idRecorrido;
    private Fase fase;
    private Grupo grupo;
    private Motivo motivo;
    private Persona persona;
    private Programa programa;
    private Tratamiento tratamiento;
    private Date fechaInicio;
    private Date fechaFin;
    private String activo; // ESTE, COMO STRING???????????????????????? (pos demomento si, como el resto de "activos")

    public Recorrido() {
    }

    public Recorrido(Fase fase, Grupo grupo, Motivo motivo, Persona persona, Programa programa, Tratamiento tratamiento, Date fechaInicio, Date fechaFin, String activo) {
        this.fase = fase;
        this.grupo = grupo;
        this.motivo = motivo;
        this.persona = persona;
        this.programa = programa;
        this.tratamiento = tratamiento;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.activo = activo; 
    }

    public Integer getIdRecorrido() {
        return this.idRecorrido;
    }

    public void setIdRecorrido(Integer idRecorrido) {
        this.idRecorrido = idRecorrido;
    }

    public Fase getFase() {
        return this.fase;
    }

    public void setFase(Fase fase) {
        this.fase = fase;
    }

    public Grupo getGrupo() {
        return this.grupo;
    }

    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

    public Motivo getMotivo() {
        return this.motivo;
    }

    public void setMotivo(Motivo motivo) {
        this.motivo = motivo;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Programa getPrograma() {
        return this.programa;
    }

    public void setPrograma(Programa programa) {
        this.programa = programa;
    }

    public Tratamiento getTratamiento() {
        return this.tratamiento;
    }

    public void setTratamiento(Tratamiento tratamiento) {
        this.tratamiento = tratamiento;
    }

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    public String getActivo() {
        return this.activo;
    }

    public void setActivo(String activo) {
        this.activo = activo;
    }

}
