package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idRol;
    private String descripcion;
    private Set<RolPersona> rolPersonas = new HashSet<RolPersona>(0);
    private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);

    public Rol() {
    }

    public Rol(String descripcion, Set<RolPersona> rolPersonas, Set<UsuarioRol> usuarioRols) {
        this.descripcion = descripcion;
        this.rolPersonas = rolPersonas;
        this.usuarioRols = usuarioRols;
    }

    public Integer getIdRol() {
        return this.idRol;
    }

    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<RolPersona> getRolPersonas() {
        return this.rolPersonas;
    }

    public void setRolPersonas(Set<RolPersona> rolPersonas) {
        this.rolPersonas = rolPersonas;
    }

    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }

    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }

}
