package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

/**
 * RolPersona generated by hbm2java
 */
public class RolPersona implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idRolPersona;
    private Persona persona;
    private Rol rol;

    public RolPersona() {
    }

    public RolPersona(Persona persona, Rol rol) {
        this.persona = persona;
        this.rol = rol;
    }

    public Integer getIdRolPersona() {
        return this.idRolPersona;
    }

    public void setIdRolPersona(Integer idRolPersona) {
        this.idRolPersona = idRolPersona;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

}
