package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idTratamiento;
    private String descripcion;
    private Set<Recorrido> recorridos = new HashSet<Recorrido>(0);
    private Set<TratamientoPrograma> tratamientoProgramas = new HashSet<TratamientoPrograma>(0);

    public Tratamiento() {
    }

    public Tratamiento(String descripcion, Set<Recorrido> recorridos, Set<TratamientoPrograma> tratamientoProgramas) {
        this.descripcion = descripcion;
        this.recorridos = recorridos;
        this.tratamientoProgramas = tratamientoProgramas;
    }

    public Integer getIdTratamiento() {
        return this.idTratamiento;
    }

    public void setIdTratamiento(Integer idTratamiento) {
        this.idTratamiento = idTratamiento;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<Recorrido> getRecorridos() {
        return this.recorridos;
    }

    public void setRecorridos(Set<Recorrido> recorridos) {
        this.recorridos = recorridos;
    }

    public Set<TratamientoPrograma> getTratamientoProgramas() {
        return this.tratamientoProgramas;
    }

    public void setTratamientoProgramas(Set<TratamientoPrograma> tratamientoProgramas) {
        this.tratamientoProgramas = tratamientoProgramas;
    }

}
