package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

/**
 * TratamientoPrograma generated by hbm2java
 */
public class TratamientoPrograma implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idTratamientoPrograma;
    private Programa programa;
    private Tratamiento tratamiento;

    public TratamientoPrograma() {
    }

    public TratamientoPrograma(Programa programa, Tratamiento tratamiento) {
        this.programa = programa;
        this.tratamiento = tratamiento;
    }

    public Integer getIdTratamientoPrograma() {
        return this.idTratamientoPrograma;
    }

    public void setIdTratamientoPrograma(Integer idTratamientoPrograma) {
        this.idTratamientoPrograma = idTratamientoPrograma;
    }

    public Programa getPrograma() {
        return this.programa;
    }

    public void setPrograma(Programa programa) {
        this.programa = programa;
    }

    public Tratamiento getTratamiento() {
        return this.tratamiento;
    }

    public void setTratamiento(Tratamiento tratamiento) {
        this.tratamiento = tratamiento;
    }

}
