package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idUsuario;
    private String usuarioNombre;
    private String usuarioClave;
    private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);

    public Usuario() {
    }

    public Usuario(String usuarioNombre, String usuarioClave, Set<UsuarioRol> usuarioRols) {
        this.usuarioNombre = usuarioNombre;
        this.usuarioClave = usuarioClave;
        this.usuarioRols = usuarioRols;
    }

    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }

    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }

    public String getUsuarioClave() {
        return this.usuarioClave;
    }

    public void setUsuarioClave(String usuarioClave) {
        this.usuarioClave = usuarioClave;
    }

    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }

    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }

}
