package com.ph3.vo;
// Generated 16-may-2017 16:53:13 by Hibernate Tools 4.3.1.Final

/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRol implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idUsuarioRol;
    private Rol rol;
    private Usuario usuario;

    public UsuarioRol() {
    }

    public UsuarioRol(Rol rol, Usuario usuario) {
        this.rol = rol;
        this.usuario = usuario;
    }

    public Integer getIdUsuarioRol() {
        return this.idUsuarioRol;
    }

    public void setIdUsuarioRol(Integer idUsuarioRol) {
        this.idUsuarioRol = idUsuarioRol;
    }

    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
